#!/bin/sh
# This scipt accepts a file in audio format and a loop number in XX format
# If target loop doesn't exist the scrit will copy directory structure of loop 01
# Afterwards it will convert the audio file to appropriate format and copy it to
# phrase.wav of the given target loop.

usage() {
    SCRIPT=`basename "$0"`
    echo "jamman-newloop: creates a new loop from the given audio/video file"
    echo "usage: $SCRIPT <input audio/video file> <loop number>"
    echo
    echo "e.g."
    echo "$SCRIPT myloop.mp3 07"
    echo
    echo "Optionally you can add time-from time-to params at the end to cut only"
    echo "a part of the file."
    echo "e.g."
    echo "$SCRIPT myloop.mp3 07 1:05 2:11"
}

if [ "$#" -lt 2 ]; then
    usage
    exit 0
fi

INPUTFILE=$1
LOOPNO=$2

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$DIR"/jamman-config

TARGET_LOOP_FOLDER=$JAMMAN_LOCAL/Patch$LOOPNO

if [ ! -d "$TARGET_LOOP_FOLDER" ]; then
    echo "Creating folder structure for loop $LOOPNO"
    cp -R "$JAMMAN_LOCAL"/Patch01 "$TARGET_LOOP_FOLDER"
fi

echo "Converting input file..."
if [ "$#" -gt 2 ]; then
    FROM=$3
    TO=$4
    ffmpeg -i "$INPUTFILE" -y -loglevel error -ss $FROM -to $TO -acodec pcm_s16le -ac 2 -ar 44100 -map_metadata -1 "$TARGET_LOOP_FOLDER"/PhraseA/phrase.wav
    echo "$INPUTFILE [$FROM-$TO]" > "$TARGET_LOOP_FOLDER"/.fromfile
else
    ffmpeg -i "$INPUTFILE" -y -loglevel error -acodec pcm_s16le -ac 2 -ar 44100 -map_metadata -1 "$TARGET_LOOP_FOLDER"/PhraseA/phrase.wav
    echo "$INPUTFILE" > "$TARGET_LOOP_FOLDER"/.fromfile
fi
touch "$TARGET_LOOP_FOLDER"/.new

echo "Created $TARGET_LOOP_FOLDER/PhraseA/phrase.wav"
